language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "iojs"
sudo: false
cache:
  directories:
    - node_modules
after_script: ./node_modules/.bin/coveralls < coverage/lcov.info
notifications:
  email: false
